"""create skus and inventory records tables

Revision ID: 296eba3522e7
Revises:
Create Date: 2026-06-08 07:43:43.227915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "296eba3522e7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("reorder_level", sa.Integer(), nullable=False),
        sa.Column("shelf_life_days", sa.Integer(), nullable=True),
        sa.Column("purchase_price", sa.Float(), nullable=False),
        sa.Column("selling_price", sa.Float(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("embedding", Vector(dim=1536), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skus_category"), "skus", ["category"], unique=False)
    op.create_index(op.f("ix_skus_code"), "skus", ["code"], unique=True)
    op.create_index(op.f("ix_skus_id"), "skus", ["id"], unique=False)
    op.create_table(
        "inventory_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("received_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("batch_number", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_records_batch_number"),
        "inventory_records",
        ["batch_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_records_id"), "inventory_records", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_records_sku_id"),
        "inventory_records",
        ["sku_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_records_sku_id"), table_name="inventory_records")
    op.drop_index(op.f("ix_inventory_records_id"), table_name="inventory_records")
    op.drop_index(
        op.f("ix_inventory_records_batch_number"), table_name="inventory_records"
    )
    op.drop_table("inventory_records")
    op.drop_index(op.f("ix_skus_id"), table_name="skus")
    op.drop_index(op.f("ix_skus_code"), table_name="skus")
    op.drop_index(op.f("ix_skus_category"), table_name="skus")
    op.drop_table("skus")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
